version: "3.8"

services:
  orderservice:
    build:
      context: .
      dockerfile: Dockerfiles/OrderService.Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__EndpointDefaults__Protocols=Http2
      - ASPNETCORE_URLS=http://0.0.0.0:5001  # (or 5001 for OrderService)
      - ASPNETCORE_HTTP_PORTS=
      - ASPNETCORE_HTTPS_PORTS=
    depends_on:
      - sqlserver

  productservice:
    build:
      context: .
      dockerfile: Dockerfiles/ProductService.Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__EndpointDefaults__Protocols=Http2
      - ASPNETCORE_URLS=http://0.0.0.0:5002  # (or 5001 for ProductService)
      - ASPNETCORE_HTTP_PORTS=
      - ASPNETCORE_HTTPS_PORTS=
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
